service: testlambdadeploy

provider:
   name: aws
   runtime: nodejs10.10
   stage: dev
   region: eu-west-2

   resources:
    Resources:
       MyBucket:
         Type: AWS::S3::Bucketww111
         Properties:
            BucketName: ${self:service}-${self:provider.stage}-randomtext





