service: testsecret

provider:
   name: aws
   runtime: nodejs10.10
   stage: dev
   region: ap-south-1

resources:
  Resources:
    Secrets:
      Type: AWS::SecretsManager::Secret
      Properties: 
        Name: ${self:service}.dev.random
        GenerateSecretString:
        SecretStringTemplate: !Sub '{"username": "${!Ref RDSUserName}"}'
        GenerateStringKey: 'password'
        PasswordLength: 16
        ExcludeCharacters: '"@/\'
      Tags:
        -
          Key: AppNam
          Value: MyApp
